### ISSUE TITLE
MIDI not detected lol

### ISSUE THREAD

**Issue by kenkodima** [markqvist/MidiKatapult#3]
Yeah, you red the title. My launchpad mini is fucked. I think it is because I changed or scrambled the wire idk.

**Comment by ExileFox** [comment]
Try replacing the wire?

**Comment by prisect** [comment]
Nope, original...

**Comment by markqvist** [comment]
Sorry, we're not tracking support requests for software I stopped maintaining more than a decade ago ;) I'll close this now, but you're welcome to continue any discussion if you want :)
